version: "3"
services:
    golang:
        container_name: golang
        build:
            context: ./
        ports:
            - 8080:8080
        volumes:
            - ./app:/app
        tty: true
        restart: always

    mysql:
        container_name: mysql
        image: mysql:latest
        ports:
            - 33000:3306
        volumes:
            - ./db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
        restart: always

    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin/phpmyadmin:latest
        ports:
            - 8081:80
        depends_on:
            - mysql
        environment:
            - PMA_PORT=3306
            - PMA_HOST=mysql
            - PMA_ARBITRARY=1
            - PMA_USER=root
            - PMA_PASSWORD=root